import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faUserSecret,
  faAngleDown,
  faAngleUp,
  faAngleLeft,
  faAngleRight,
  faHouse,
  faMap,
  faEarthAmericas,
  faComment,
  faCircleUser,
  faPlus,
  faEllipsisVertical,
  faXmark,
  faTriangleExclamation,
  faBell,
  faLayerGroup,
  faInfo,
  faPencil,
  faLocationDot,
  faLocationCrosshairs,
  faMagnifyingGlass,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faCarSide,
  faShop,
  faHouseChimneyWindow,
  faDog,
  faPlane,
  faCartShopping,
  faBuilding,
  faBriefcase,
  faSchool,
  faCampground,
  faCity,
} from '@fortawesome/free-solid-svg-icons'

export const registerIcons = () => {
  library.add(faUserSecret)
  library.add(faAngleDown)
  library.add(faAngleUp)
  library.add(faAngleLeft)
  library.add(faAngleRight)
  library.add(faHouse)
  library.add(faMap)
  library.add(faEarthAmericas)
  library.add(faComment)
  library.add(faCircleUser)
  library.add(faPlus)
  library.add(faEllipsisVertical)
  library.add(faXmark)
  library.add(faTriangleExclamation)
  library.add(faBell)
  library.add(faLayerGroup)
  library.add(faInfo)
  library.add(faPencil)
  library.add(faLocationDot)
  library.add(faLocationCrosshairs)
  library.add(faMagnifyingGlass)
  library.add(faMagnifyingGlassPlus)
  library.add(faMagnifyingGlassMinus)
  library.add(faCarSide)
  library.add(faShop)
  library.add(faHouseChimneyWindow)
  library.add(faDog)
  library.add(faPlane)
  library.add(faCartShopping)
  library.add(faBuilding)
  library.add(faBriefcase)
  library.add(faSchool)
  library.add(faCampground)
  library.add(faCity)
}
